const express = require('express')
const router = express.Router()
const { homePage, login, logout } = require('./controllers/loginController');
const { registerPage, validate, verify } = require('./controllers/registerController');
const { applicationFormPage, applicationFormSubmit, downloadPDF } = require('./controllers/applicationFormController');
const { studentPage, submitReport, downloadReport, removeReport } = require('./controllers/studentController');
const { supervisorPage, assignRAC, racSubmit } = require('./controllers/supervisorController');
const { supervisorApprovalController } = require('./controllers/supervisorApprovalController');
const { prcRegistrationApproval, prcRegistrationApprovalSubmit, prcReportApproval, prcReportApprovalSubmit, prcVivaReport, prcVivaReportSubmit, downloadVivaReport, prcTitleChange, prcTitleChangeSubmit, prcRegistrationExtension, prcRegistrationExtensionSubmit } = require('./controllers/prcController');
const { dcRegistrationApproval, dcRegistrationApprovalSubmit,dcReportApproval, dcReportApprovalSubmit, dcVivaReport, dcTitleChange, dcTitleChangeSubmit, dcRegistrationExtension, dcRegistrationExtensionSubmit, dcExaminerApproval, dcExaminersList, dcExaminerApprovalSubmit } = require('./controllers/dcController');
const { specialPage, specialSearchPage } = require('./controllers/specialController');
const getFaculties = require('./apis/getFaculties.js');
const getDepartments = require('./apis/getDepartments.js');
const getProfessors = require('./apis/getProfessors.js');
const getProfessorDesignation = require('./apis/getProfessorDesignation.js');
const { examinerPage,addExaminer,addExam } = require('./controllers/examinerController');

router.get("/", homePage);
router.post("/login", login);
router.get("/logout", logout);
router.get("/registerPage", registerPage);
router.get("/removeReport",removeReport);
router.post("/validate", validate);
router.post("/verify", verify);
router.get("/applicationFormPage", applicationFormPage);
router.post("/applicationFormSubmit", applicationFormSubmit);
router.get("/downloadPDF", downloadPDF);
router.get("/studentPage", studentPage);
router.get("/supervisorPage", supervisorPage);
router.get("/assignRAC.html", assignRAC);
router.post("/racSubmit", racSubmit);
router.post("/supervisorApproval", supervisorApprovalController);
router.get("/prcRegistrationApproval", prcRegistrationApproval);
router.post("/prcRegistrationApprovalSubmit", prcRegistrationApprovalSubmit);
router.get("/prcReportApproval",prcReportApproval);
router.post("/prcReportApprovalSubmit",prcReportApprovalSubmit);
router.get("/prcVivaReport",prcVivaReport);
router.post("/prcVivaReportSubmit",prcVivaReportSubmit);
router.get("/downloadVivaReport",downloadVivaReport);
router.get("/prcTitleChange",prcTitleChange);
router.post("/prcTitleChangeSubmit",prcTitleChangeSubmit);
router.get("/prcRegistrationExtension",prcRegistrationExtension);
router.post("/prcRegistrationExtensionSubmit",prcRegistrationExtensionSubmit);
router.get("/dcRegistrationApproval", dcRegistrationApproval);
router.post("/dcRegistrationApprovalSubmit", dcRegistrationApprovalSubmit);
router.get("/dcReportApproval",dcReportApproval);
router.post("/dcReportApprovalSubmit",dcReportApprovalSubmit);
router.get("/dcVivaReport",dcVivaReport);
router.get("/dcTitleChange",dcTitleChange);
router.post("/dcTitleChangeSubmit",dcTitleChangeSubmit);
router.get("/dcRegistrationExtension",dcRegistrationExtension);
router.post("/dcRegistrationExtensionSubmit",dcRegistrationExtensionSubmit);
router.get("/dcExaminerApproval",dcExaminerApproval);
router.post("/dcExaminerApprovalSubmit",dcExaminerApprovalSubmit);
router.get("/dcExaminersList",dcExaminersList);
router.get("/myStudents",examinerPage);
router.post("/selectExaminer",addExaminer);
router.post("/addedExaminer",addExam);
router.post("/specialDB", specialPage);
router.post("/searchDB", specialSearchPage);
router.post("/submitReport", submitReport);
router.get("/downloadReport", downloadReport);
router.get("/api/faculties", getFaculties);
router.get("/api/departments", getDepartments);
router.get("/api/professors", getProfessors);
router.get("/api/designation", getProfessorDesignation);

module.exports = router;